# mkdocs.yml - VERSO COM MODO CLARO/ESCURO

site_name:  Comunidade Officina's

copyright: >-
  <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">
    CC BY-SA 4.0
  </a>
  - eduardo.charquero@gmail.com

# --- SEO 'nav' ---
nav:
  -  'In铆cio': 'index.md'
  -  'Vis茫o Geral': 'Visao_Geral.md'
  -  'Servidores':
    - 'DHCP Server': 'DHCP_Server.md'
    - 'DNS Server': 'DNS_Server.md'
    - 'Servidor de Firewall':
      - 'Firewall': 'Firewall.md'
    - 'Servidor Proxy':
      - 'Proxy Squid': 'Squid_proxy_puro.md'
    - 'MkDocs Server': 'Mkdocs_Server.md'
    - 'NFS Server': 'NFS_Server.md'
    - 'Servidor de Arquivos':
      - 'Fileserver': 'Fileserver.md'
    - 'Controladores de Dom铆nio':
      - 'PDC Server': 'PDC_Controlador_de_Dominio_Primario.md'

  -  'Distros Linux':
    - 'OpenSUSE Linux': 'OpenSUSE_Linux.md'
    - 'Devuan Linux': 'Devuan_Linux.md'

  -  'M贸dulos LPI':
    - 'LPI Aula de Introdu莽茫o': 'LPI_Aula_de_introducao.md'

    - 'M贸dulo LPIC-101':
      - '101.1':
        - 'LPIC-101.1_Identificacao_e_configuracao_de_hardware.md'
        - 'LPIC-101.1_Aula_pratica.md'
      - '101.2':
        - 'LPIC-101.2_Processo_de_inicializacao_do_linux.md'
        - 'LPIC-101.2_Aula_pratica.md'
        - 'LPIC-101.2_UEFI_NVRAM_Aula_pratica.md'
      - '101.3':
        - 'LPIC-101.3_Runlevel_shutdown_e_reboot.md'
        - 'LPIC-101.1_Aula_pratica.md'

    - 'M贸dulo LPIC-102':
      - '102.1': 'LPIC-102.1_Particionamento_de_discos.md'
      - '102.2': 'LPIC-102.2_Gerenciamento_do_boot_manager.md'

    - 'M贸dulo LPIC-103':
      - '103.1': 'LPIC-103.1_Shell_e_linha_de_comandos.md'
      - 'Aula 02': 'Modulo_103.1-aula02.md'
      - 'Aula 03': 'Modulo_103.1-aula03.md'
      - 'Aula 04': 'Modulo_103.1-aula04.md'
      - 'Aula 05': 'Modulo_103.1-aula05.md'

    - 'M贸dulo 103.2 - Processamento de Texto':
      - 'Aula 01': 'Modulo_103.2-aula01.md'

  -  'Outros assuntos':
    - 'Universo *NIX': 'Universo_NIX.md'
    - 'Aircrack-NG': 'Aircrack-NG.md'
    - 'Linux no Dom铆nio': 'Ingressar_Linux_no_dominio.md'
    - 'O SystemD': 'Systemd.md'
    - 'FHS': 'FHS.md'
    - 'RAID': 'Raid.md'
    - 'Permiss玫es Linux 01': 'Permissoes_Linux-01.md'
    - 'Permiss玫es Linux 02':

